### ISSUE TITLE
Setup KanBan

### ISSUE THREAD

**Issue by gjuliao** [gjuliao/recipe_app#12]
- [Link to github project](https://github.com/users/gjuliao/projects/1/views/1)
- Group of 2 - @gjuliao and @Vgonma

**Comment by 1GORDON** [comment]
##
## Hi @gjuliao & @Vgonma ✋

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as invalid and won't affect the number of your weekly reviews.

- [ ] You have submitted a project with a broken link to your GitHub project. Kindly fix this broken link and resubmit for review.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gjuliao** [comment]
Hi @1GORDON, the link seems to be working just fine. @Vgonma Do you have issues opening it?

**Comment by Vgonma** [comment]
I don't have any problems opening it

**Comment by tresorsawasawa** [comment]
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @gjuliao and @Vgonma 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- Good issue description ✔ 

## Required changes :recycle: :recycle: 

- [ ] To correctly match all project's requirements and not having duplicate cards, I think it would be better if you update the below card's name to **Recipe Details** instead of **Recipe List**.
![Screenshot from 2023-04-17 17-56-17](https://user-images.githubusercontent.com/83042742/232543966-aa0b6df6-ec0d-40f8-af58-217546d446b3.png)
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gjuliao** [comment]
Title changed as suggested.

**Comment by 1GORDON** [comment]
# Status: APPROVED 🟢 

Hi @gjuliao & @Vgonma ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
